# Fonts
font_family      CaskaydiaCove Nerd Font
font_size        19.0

disable_ligatures no
enable_audio_bell no

shell zsh
shell_integration disabled

url_style curly

remember_window_size no

corsor_blink_interval 0

scrollbar_handle_opactiy 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0

confirm_os_window_close 0

sync_to_monitor no

# Window
background_opacity 0.8
window_padding_width 0 0

# Scrolling
scrollback_lines 10000

# Cursor
cursor #F5E0DC
cursor_text_color #1E1D2F

# Colors - Catppuccin Macchiato theme
background #1E1D2F
foreground #D9E0EE

# Normal colors
color0  #6E6C7E
color1  #F28FAD
color2  #ABE9B3
color3  #FAE3B0
color4  #96CDFB
color5  #F5C2E7
color6  #89DCEB
color7  #D9E0EE

# Bright colors
color8  #988BA2
color9  #F28FAD
color10 #ABE9B3
color11 #FAE3B0
color12 #96CDFB
color13 #F5C2E7
color14 #89DCEB
color15 #D9E0EE

# Indexed colors
color16 #F8BD96
color17 #F5E0DC

# Environment
env LANG=en_US.UTF-8
env LC_CTYPE=en_US.UTF-8
env TERM=kitty

map ctrl+shift+r load_config_file
