swipe:
  3:
    up:
      command: "xdotool key super+shift+s" # History forward
    down:
      command: "xdotool key super+shift+w" # History back
    left:
      command: "xdotool key super+shift+s" # History forward
    right:
      command: "xdotool key super+shift+w" # History back
  4:
    left:
      command: "xdotool key super+z"
    right:
      command: "xdotool key super+x"

threshold:
  swipe: 0.5

interval:
  swipe: 0.5
