# Autostart necessary processes (like notifications daemons, status bars, etc.)

exec-once = swww-daemon
exec-once = hyprpaper
exec-once = waybar
exec-once = swaync
exec-once = systemctl --user start hyprpolkitagent
exec-once = blueman-applet

# Added for the lock screen setup
exec-once = hypridle

# Sync cursor theme
exec-once = hyprctl setcursor Bibata-Modern-Classic 20
