#!/bin/bash

# Directory containing wallpapers
WALLPAPER_DIR="$HOME/dotfiles/Wallpapers"

# Command to set wallpaper using Nitrogen
# feh --bg-fill --randomize $WALLPAPER_DIR/*

export DISPLAY=:0
random_wallpaper=$(ls $WALLPAPER_DIR | shuf -n 1)

# Command to set wallpaper using Nitrogen
nitrogen --set-zoom-fill "$WALLPAPER_DIR/$random_wallpaper"
