#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/Projects ~/College/ ~/ ~/dotfiles ~/.config/ ~/.config/nvim/ -mindepth 1 -maxdepth 2 -type d | sort -u | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux -u new-session -c "$selected"
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
if ! tmux has-session -t="$selected_name" 2> /dev/null; then
    tmux -u new-session -ds "$selected_name" -c "$selected"
fi

tmux -u attach -t "$selected_name"
